image: registry.kriese.eu/jobs/docker/android

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  interruptible: true
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - app/build
      - .gradle

test:
  interruptible: true
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - app/build
      - .gradle
